# Generated by Django 4.2.7 on 2023-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_name_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totpkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
