# Generated by Django 4.2.7 on 2023-12-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_totpkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpkey',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
